Adding Bhashini API-based Translation Library
ULCA-IN/anuvaad-client-sdk pull request #1
Opened 2023-07-29 10:08 UTC by stupiddint

2023-08-01 04:48 UTC, mathewjpallan commented on config/serviceId.js
> +            'ulcaApiKey': '25e21b8af7-4d7a-4d29-89d4-6d7a3e745e12'
Do not have API keys in code.

2023-08-01 04:48 UTC, mathewjpallan commented on src/asr+nmt+tts.js
> +    const url = 'https://dhruva-api.bhashini.gov.in/services/inference/pipeline'
URLs have to be in config

2023-08-01 04:48 UTC, mathewjpallan commented on src/asr+nmt+tts.js
> +    return await axios.post(url, payload, { headers }).then(function (res) {
the setting of headers, the post method etc should be in a base class. This code seems to be repeating in all the js files.

2023-08-01 04:48 UTC, mathewjpallan commented on src/asr.js
> +        "pipelineTasks": [
The pipelineTasks should all be configuration and not hardcoded in the code

2023-08-10 06:43 UTC, rajeevsathish requested changes

2023-08-10 06:43 UTC, rajeevsathish commented on src/utils/baseApi.js
> +import axios from "axios";
axios gives you post methods directly why do you need a wrapper on that

2023-08-10 06:46 UTC, rajeevsathish commented on config/payload.js
> +const getTtsPipeline = async (sourceLang, gender) => {
methods need to have proper doc so that anyone who reads the method can understand the method easily please refer https://jsdoc.app/about-getting-started.html

2023-09-07 06:02 UTC, merged